# Run all tests, linters, code analysis and other QA tasks on
# every push to master and PRs.
name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
# To SSH into the runner to debug a failure, add the following step before
# the failing step
#    - uses: lhotari/action-upterm@v1
#      with:
#        limit-access-to-actor: true

# Prevent multiple jobs running after fast subsequent pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  test_314:
    name: "Python 3.14 Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/nix-shell
        with:
          cachix_auth_token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run linters and unit tests
        run: |
          nix-shell --run "make tests frozen=1"
      - name: Run tests for the singlefile example
        run: |
          cd examples/singlefile
          nix-shell --run "uv run --no-sync python -m unittest app"
      - name: Run tests for the todoapp example
        run: |
          cd examples/todoapp
          nix-shell --run "uv run --no-sync python -m unittest tests"
      - name: Run tests for the splitfile example
        run: |
          cd examples/splitfile
          nix-shell --run "uv run --no-sync python -m unittest tests"
      - name: Save coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: htmlcov
          path: htmlcov/
  test_311:
    name: "Python 3.11 Tests (oldest supported dependencies)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/nix-shell
        with:
          cachix_auth_token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run unit tests against the oldest supported dependencies
        run: |
          cp uv-oldest.lock uv.lock
          nix-shell --run "uv sync --frozen --python 3.11"
          nix-shell --run "make tests python=3.11 frozen=1"
      - name: Run tests for the singlefile example
        run: |
          cd examples/singlefile
          nix-shell --run "uv run --no-sync --python 3.11 python -m unittest app"
      - name: Run tests for the todoapp example
        run: |
          cd examples/todoapp
          nix-shell --run "uv run --no-sync --python 3.11 python -m unittest tests"
      - name: Run tests for the splitfile example
        run: |
          cd examples/splitfile
          nix-shell --run "uv run --no-sync --python 3.11 python -m unittest tests"
